/schedule:
    get:
      summary: "Get schedule for month"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "find"
      produces:
      - "application/xml"
      - "application/json"
      parameters: 
      - name: "status"
      - in: "body"
        name: "body"
        description: "Updated user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "Schedule"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Pet"

          '200':
    description: A user object.
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/User'   # Reference to an object
        400:
          description: "Invalid status value"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"




















                